ankieta_nfz/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^', include('survey.urls', namespace='survey')),
    # Django Admin, use {% url 'admin:index' %}
    url(r'^$', RedirectView.as_view(url=settings.REDIRECT_HOME)),
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^tinymce/', include('tinymce.urls')),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

survey/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<participant>[\d-]+)/(?P<password>[\d-]+)/$',
        views.SurveyDispatchView.as_view(),
        name="list"),
    url(r'^(?P<participant>[\d-]+)/(?P<password>[\d-]+)/~print$',
        views.SurveyPrintDispatchView.as_view(),
        name="print"),
    url(r'^(?P<participant>[\d-]+)/(?P<password>[\d-]+)/~accept$',
        views.SurveyAcceptView.as_view(),
        name="accept"),
    url(r'^(?P<participant>[\d-]+)/(?P<password>[\d-]+)/hospital-(?P<hospital>[\d-]+)/$',
        views.HospitalSurveyView.as_view(),
        name="survey"),
    url(r'^(?P<participant>[\d-]+)/(?P<password>[\d-]+)/question-(?P<question>[\d-]+)/$',
        views.QuestionSurveyView.as_view(),
        name="survey"),

]

survey/models.py
import random
from collections import namedtuple

from autoslug.fields import AutoSlugField
from django.contrib.sites.models import Site
from django.core.urlresolvers import reverse
from django.db import models
from django.db.models import F, Count
from django.db.models.functions import Cast
from django.db.models.signals import post_delete, post_save
from django.dispatch import receiver
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from model_utils import Choices
from model_utils.models import TimeStampedModel
from tinymce.models import HTMLField

LogEntry = namedtuple('LogEntry', ['status', 'text'])
LinkedHospital = namedtuple('LinkedHospital', ['obj', 'link', 'status'])
LinkedCategory = namedtuple('LinkedCategory', ['obj', 'question_set'])
LinkedQuestion = namedtuple('LinkedQuestion', ['obj', 'link', 'status'])


def get_secret():
    return random.randint(10**4, 10**5 - 1)


class NationalHealtFundQuerySet(models.QuerySet):
    pass


@python_2_unicode_compatible
class NationalHealtFund(TimeStampedModel):
    name = models.CharField(verbose_name=_("Name"), max_length=150, help_text=_("Branch name"))
    email = models.EmailField(verbose_name=_("E-mail"),
                              help_text=_("E-mail to a branch of the national health fund"))
    identifier = models.CharField(verbose_name=_("Identifier"),
                                  max_length=15,
                                  help_text=_("ID data to an external computer system"))
    objects = NationalHealtFundQuerySet.as_manager()

    class Meta:
        verbose_name = _("National Healt Fund")
        verbose_name_plural = _("National Healt Funds")
        ordering = ['created', ]

    def __str__(self):
        return self.name


class HospitalQuerySet(models.QuerySet):

    def answer_fetch(self, participant):
        prefetch = models.Prefetch(lookup='answer_set',
                                   to_attr='answer_participant',
                                   queryset=Answer.objects.filter(participant=participant))
        return self.prefetch_related(prefetch)

    def linked(self, participant, password):
        linked_hospitals = []
        for hospital in self:
            link = reverse('survey:survey', kwargs={'password': password,
                                                    'participant': participant,
                                                    'hospital': hospital.pk})
            link = 'http://%s%s' % (Site.objects.get_current().domain, link)
            linked = LinkedHospital(obj=hospital,
                                    link=link,
                                    status=len(hospital.answer_participant) > 0)
            linked_hospitals.append(linked)
        return linked_hospitals


@python_2_unicode_compatible
class Hospital(TimeStampedModel):
    health_fund = models.ForeignKey(NationalHealtFund, verbose_name=_("National Healt Fund"))
    name = models.CharField(verbose_name=_("Name"), max_length=250)
    email = models.EmailField(verbose_name=_("E-mail"))
    identifier = models.CharField(
        verbose_name=_("Identifier"),
        help_text=_('The internal identifier used to connect foundation database'),
        max_length=15,
        blank=True)
    objects = HospitalQuerySet.as_manager()

    class Meta:
        verbose_name = _("Hospital")
        verbose_name_plural = _("Hospitals")
        ordering = ['created', ]

    def __str__(self):
        return self.name


class SurveyQuerySet(models.QuerySet):

    def prefetch_full_content(self):
        return self.prefetch_related('category_set__question_set__subquestion_set')

    def with_db_subquestion_count(self):
        return self.annotate(db_subquestion_count=Count('category__question__subquestion',
                                                        distinct=True))


@python_2_unicode_compatible
class Survey(TimeStampedModel):
    STYLE = Choices((0, 'total', _('Total view')),
                    (1, 'hospital', _('Hospital view')),
                    (2, 'question', _('Question view')))
    PRINT_STYLE = Choices((0, 'per_hospital', _('Print per hospital')),
                          (1, 'per_participant', _('Print per participant')))
    title = models.CharField(verbose_name=_("Title"), max_length=250)
    slug = AutoSlugField(populate_from='title', verbose_name=_("Slug"), unique=True)
    welcome_text = HTMLField(verbose_name=_("Welcome text"), blank=True)
    instruction = HTMLField(verbose_name=_("Instruction"), blank=True)
    end_text = HTMLField(verbose_name=_("End text"), blank=True)
    submit_text = HTMLField(verbose_name=_("Submit text"), blank=True)
    subquestion_count = models.IntegerField(verbose_name=_("Total number of subquestion"),
                                            default=0)
    participants = models.ManyToManyField(NationalHealtFund,
                                          verbose_name=_("Participants"),
                                          through="Participant")
    style = models.IntegerField(choices=STYLE, default=STYLE.question)
    print_style = models.IntegerField(choices=PRINT_STYLE, default=PRINT_STYLE.per_participant)
    objects = SurveyQuerySet.as_manager()

    def _count_msg(self, obj, attribute, found=None, missing=None):
        count = len(getattr(obj, attribute).all())
        rel_name = getattr(obj, attribute).model._meta.verbose_name
        obj_name = obj._meta.verbose_name
        missing = missing or "%s in %%s %s is missing" % (rel_name, obj_name)
        found = found or "%%d %s exists in %%s %s" % (rel_name, obj_name)
        if count:
            return LogEntry(True, found % (count, obj))
        return LogEntry(False, missing % (obj))

    def perform_audit(self):
        log = []
        log.append(LogEntry(None, "Audit %s survey" % (str(self))))
        # Entities auditing
        log.append(self._count_msg(self, 'participants'))
        log.append(self._count_msg(self, 'category_set'))

        for category in self.category_set.all():
            log.append(LogEntry(None, "Audit %s category" % (str(category))))
            log.append(self._count_msg(category, 'question_set'))

            for question in category.question_set.all():
                log.append(LogEntry(None, "Audit %s question" % (str(question))))
                log.append(self._count_msg(question, 'subquestion_set'))
        return log

    def update_subquestion_counter(self):
        obj = Survey.objects.with_db_subquestion_count().get(pk=self.pk)
        obj.subquestion_count = obj.db_subquestion_count
        obj.save(update_fields=["subquestion_count"])

    class Meta:
        verbose_name = _("Survey")
        verbose_name_plural = _("Surveys")
        ordering = ['created', ]

    def __str__(self):
        return self.title


class ParticipantQuerySet(models.QuerySet):

    def with_survey(self):
        return self.prefetch_related('survey__category_set__question_set__subquestion_set')

    def with_hospital(self):
        return self.prefetch_related('health_fund__hospital_set')

    def with_db_answer_count(self):
        return self.annotate(db_answer_count=Count('answer', distinct=True))

    def with_progress_stats(self):
        def fl(expr):
            return Cast(expr, models.FloatField())
        qs = self.annotate(hospital_count=Count('health_fund__hospital', distinct=True))
        up = F('answer_count')
        down = F('survey__subquestion_count') * F('hospital_count')
        expr = (up / down) * 100
        qs = qs.annotate(progress=expr)  # Due django casting bug available in Python as int only
        return qs


class Participant(TimeStampedModel):
    health_fund = models.ForeignKey(NationalHealtFund,
                                    verbose_name=_("National Healt Fund"),
                                    on_delete=models.CASCADE)
    survey = models.ForeignKey(Survey, verbose_name=_("Survey"), on_delete=models.CASCADE)
    password = models.CharField(verbose_name=_("Password"), default=get_secret, max_length=15)
    answer_count = models.IntegerField(verbose_name=_("Answer count"), default=0)
    accept_on = models.DateTimeField(null=True, blank=True, verbose_name=_("Accept on"))
    objects = ParticipantQuerySet.as_manager()

    def get_answer_count(self):
        return self.answer_count

    def get_hospital_count(self):
        if not hasattr(self, 'hospital_count'):
            self.hospital_count = Hospital.objects.filter(health_fund=self.health_fund_id).count()
        return self.hospital_count

    def get_subquestion_count(self):
        return self.survey.subquestion_count

    def get_required_count(self):
        return self.get_hospital_count() * self.get_subquestion_count()

    def get_progress(self):
        return self.get_answer_count() / self.get_required_count() * 100

    def get_progress_display(self):
        return "{0:d} / {1:d} = {2:.2f} %".format(self.get_answer_count(),
                                                  self.get_required_count(),
                                                  self.get_progress())

    def get_absolute_url(self, *args, **kwargs):
        return reverse('survey:list', kwargs={'participant': str(self.id),
                                              'password': self.password})

    class Meta:
        verbose_name = _("Participant")
        verbose_name_plural = _("Participants")
        ordering = ['created']
        index_together = [
            ["id", "password"],
        ]


class CategoryQuerySet(models.QuerySet):

    def linked(self, **kwargs):
        return [LinkedCategory(question_set=category.question_set.linked(**kwargs),
                               obj=category) for category in self]


@python_2_unicode_compatible
class Category(TimeStampedModel):
    survey = models.ForeignKey(to=Survey, verbose_name=_("Survey"))
    name = models.CharField(verbose_name=_("Name"), max_length=100)

survey/templates/survey/_form_print.html
{% for category, question_set in form.grouped_fields %}
    <h2>{{category}}</h2>
    {% for question, subquestion_set in question_set %}
        <h3>{{question}}</h3>
        {% for subquestion, field in subquestion_set %}
            <div>
            {{ field.label }}: [{{field.initial}}]
            </div>
        {% endfor %}
    {% endfor %}
{% endfor %}

survey/templates/survey/_print.html
{% load staticfiles i18n %}<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
    <style type="text/css">
@media print {
    *,
    *:before,
    *:after {
        background: transparent !important;
        color: #000 !important;
        box-shadow: none !important;
        text-shadow: none !important;
    }

    a,
    a:visited {
        text-decoration: underline;
    }

/*    a[href]:after {
        content: " (" attr(href) ")";
    }

    abbr[title]:after {
        content: " (" attr(title) ")";
    }

    a[href^="#"]:after,
    a[href^="javascript:"]:after {
        content: "";
    }*/

    pre,
    blockquote {
        border: 1px solid #999;
        page-break-inside: avoid;
    }

    thead {
        display: table-header-group;
    }

    tr,
    img {
        page-break-inside: avoid;
    }

    img {
        max-width: 100% !important;
    }

    p,
    h2,
    h3 {
        orphans: 3;
        widows: 3;
    }

    h2,
    h3 {
        page-break-after: avoid;
    }
    .question {
        page-break-inside: avoid;
    }
}
    .seperator {
            text-align: center;
            display: block;
    }
    td, th{
    border: black solid 2px;
    }
    .col-first {
        width: 50%;
    }
    .table {
        width
    }
    </style>
</head>

<body>
  {% block content %}
  {% endblock %}
  <script type="text/javascript">
    window.print();
  </script>
</body>

</html>

survey/templates/survey/base.html
{% load staticfiles i18n %}<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="">
<!--<![endif]-->

<head>
    {% block head %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=PT+Sans" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/normalize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    {% endblock head %}
</head>

<body>
    {% block body%}
    <div class="header">
        <div class="container">
            <div class="header-top">
                <a href="http://rodzicpoludzku.pl/">
                    <img src="{% static 'img/logo.png' %}" alt="" height="130" class="header-logo">
                </a>
            </div>
        </div>
    </div>
    <div class="content">
        <div class="container">
            <div class="page-content">
                {% include "partials/_flash_messages.html" %}
                {% block content %}
                {% endblock content%}
                <p class="text-center">
                    Projekt dofinansowany ze środków Programu Fundusz Inicjatyw Obywatelskich<br>
                    <img src="{% static 'img/logo-fio.jpg' %}" width="215" height="134" alt="Programu Fundusz Inicjatyw Obywatelskich">
                </p>
            </div>
        </div>
    </div>
    {% endblock body %}
    {% block javscripts %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script>
    window.jQuery || document.write('<script src="{% static 'js/vendor/jquery-1.11.2.min.js'%}"><\/script>')
    </script>
    <script src="{% static 'js/main.js' %}"></script>
    {% endblock javscripts %}
</body>

</html>

survey/templates/survey/hospital_form.html
{% extends 'survey/base.html' %}
{% load i18n %}

{% block content %}
<h1>{{survey}} <small>{{hospital}}</small></h1>
{{ survey.instruction | safe }}
<form method="POST">

{% csrf_token %}
  {% for category, question_set in form.grouped_fields %}
      <h3>{{category}}</h3>
      {% for question, subquestion_set in question_set %}
          <h4>{{question}}</h4>
          {% for subquestion, field in subquestion_set %}
              <div>
                {{ field.errors }}
                <div class="form-group">
                  <div class="form-group-label">
                    {{ field.label_tag }}
                  </div>
                  <div class="form-group-input">
                    {{ field }}
                  </div>
                </div>
              </div>
          {% endfor %}
      {% endfor %}
  {% endfor %}
  <div>
    {{ survey.end_text | safe }}
  </div>
  <div>
    <button type="submit" class="btn-brand">{% trans 'Save answer' %}</button>
  </div>
  <br>
  <br>
  <br>
  <a href="{{survey_list_url}}" class="btn-brand">Powrót do listy szpitali</a>
</form>
{% endblock %}

survey/templates/survey/hospital_list.html
{% extends 'survey/base.html' %}
{% load i18n %}

{% block content %}
<h1>{{survey}}</h1>
{{ survey.welcome_text | safe }}
<table class="table">
  <thead>
    <th>Obiekt</th>
    <th>Status</th>
  </thead>
  <tbody>
  {% for object, link, status in linked_hospitals %}
    <tr>
      <td>
        <a href="{{link}}">{{object}}</a>
      </td>
      <td>
        {% if status %}
          <i class="fa fa-thumbs-up" aria-hidden="true"></i> Zapisano wyniki
        {% else %}
          <i class="fa fa-hourglass" aria-hidden="true"></i> Oczekuje na przesłanie danych
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
</ul>

<a href="{{print_url}}" class="btn-brand">{% trans 'Print' %}</a>
{% endblock %}

survey/templates/survey/participant_email.html
Szanowni Państwo,

Uprzejmie potwierdzamy zapisanie odpowiedzi {{participant.health_fund}} na pytania. 

Poniżej przedstawiamy zestawienie udzielonych odpowiedzi.:
{% for category, question_set in object_list %}# {{category}}
{% for question, subquestion_set in question_set %}## {{question}}
{% for subquestion, answer_set in subquestion_set %}### {{subquestion}}
{% for hospital, data in answer_set %}- {{hospital}}: {{data}}
{% endfor %}
{% endfor %}{% endfor %}
{% endfor %}
Z poważaniem,

survey/templates/survey/participant_print.html
{% extends 'survey/_print.html' %}
{% load staticfiles %}
{% block content %}
  <a href="http://rodzicpoludzku.pl/">
      <img src="{% static 'img/logo.png' %}" alt="" height="130" class="header-logo">
  </a>
  {% for category, question_set in participant_form.grouped_fields %}
  <h2>{{category}}</h2>
  {% for question, subquestion_set, hospital_set in question_set %}
  <h3>{{question}}</h3>
  <table>
      <thead>
        <tr>
            <th class="col-{{subquestion_set|length}} col-first">&nbsp;</td>
            {% for subquestion in subquestion_set %}
            <th class="col-{{subquestion_set|length}}">{{subquestion}}</th>
            {% endfor %}
        </tr>
      </thead>
      <tbody>
        {% for hospital, hospitalsubquestion_set in hospital_set %}
        <tr>
            <td class="col-{{hospitalsubquestion_set|length}} col-first">{{hospital}}</th>
            {% for field in hospitalsubquestion_set %}
            <td class="col-{{hospitalsubquestion_set|length}}">
                <div>
                    {{ field.initial }}
                </div>
            </td>
            {% endfor %}
        </tr>
        {% endfor %}
      </tbody>
  </table>
  {% endfor %}
  {% endfor %}
{% endblock %}

survey/templates/survey/question_list.html
{% extends 'survey/base.html' %}
{% load i18n %}

{% block content %}
<h1>{{survey}}</h1>
{{ survey.welcome_text | safe }}
{% for category, question_set in linked_categories %}
<h2>{{category}}</h2>
<table class="table">
  <thead>
    <th>Obiekt</th>
    <th>Status</th>
  </thead>
  <tbody>
  {% for object, link, status in question_set %}
    <tr>
      <td>
        <a href="{{link}}">{{object}}</a>
      </td>
      <td>
        {% if status %}
          <i class="fa fa-thumbs-up" aria-hidden="true"></i> Zapisano wyniki
        {% else %}
          <i class="fa fa-hourglass" aria-hidden="true"></i> Oczekuje na przesłanie danych
        {% endif %}
      </td>
    </tr>
  {% endfor %}
  </tbody>
</table>
<a href="{{accept_url}}" class="btn-brand" name="next" value="yes">{% trans 'Accept answer' %}</button>
</ul>
{% endfor %}
<a href="{{print_url}}" class="btn-brand">{% trans 'Print' %}</a>
{% endblock %}

survey/templates/survey/survey_admin_base.html
{% extends 'admin/object_history.html' %}
{% load i18n admin_urls %}
{% block breadcrumbs %}
<div class="breadcrumbs">
<a href="{% url 'admin:index' %}">{% trans 'Home' %}</a>
&rsaquo; <a href="{% url 'admin:app_list' app_label=opts.app_label %}">{{ opts.app_config.verbose_name }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'changelist' %}">{{ opts.verbose_name_plural }}</a>
&rsaquo; <a href="{% url opts|admin_urlname:'change' object.pk|admin_urlquote %}">{{ object|truncatewords:"18" }}</a>
&rsaquo; {{ title }}
</div>
{% endblock %}

survey/templates/survey/survey_admin_overview.html
{% extends 'survey/survey_admin_base.html' %}
{% load i18n %}

{% block content %}
<ul>
{% for category in object.category_set.all %}
    <li>{% trans 'Category' %}: {{category}} [<a href="{% url 'admin:survey_category_change' category.id %}">{% trans 'Edit' %}</a>]<ul>
    {% for question in category.question_set.all %}
        <li>{% trans 'Question' %}: {{question}} [<a href="{% url 'admin:survey_question_change' question.id %}">{% trans 'Edit' %}</a>] <ul>
        {% for subquestion in question.subquestion_set.all %}
            <li>{% trans 'Subquestion' %}: {{subquestion}} ({{subquestion.get_kind_display}})  [<a href="{% url 'admin:survey_subquestion_change' subquestion.id %}">{% trans 'Edit' %}</a>]</li>
        {% endfor %}
        </ul></li>
    {% endfor %}
    </ul></li>
{% endfor %}
</ul>
{% endblock %}

survey/templates/survey/survey_admin_preview.html
{% extends 'survey/survey_admin_base.html' %}
{% load i18n %}

{% block content %}
<ul>
{% for category in object.category_set.all %}
    <li>{% trans 'Category' %}: {{category}} [<a href="{% url 'admin:survey_category_change' category.id %}">{% trans 'Edit' %}</a>]<ul>
    {% for question in category.question_set.all %}
        <li>{% trans 'Question' %}: {{question}} [<a href="{% url 'admin:survey_question_change' category.id %}">{% trans 'Edit' %}</a>] <ul>
        {% for subquestion in question.subquestion_set.all %}
            <li>{% trans 'Subquestion' %}: {{subquestion}} ({{subquestion.get_kind_display}})  [<a href="{% url 'admin:survey_subquestion_change' category.id %}">{% trans 'Edit' %}</a>]</li>
        {% endfor %}
        </ul></li>
    {% endfor %}
    </ul></li>
{% endfor %}
</ul>
{% endblock %}

survey/templates/survey/survey_admin_stats.html
{% extends 'survey/survey_admin_base.html' %}

{% load i18n %}
{% block content %}
<style>
.bar {
  position: relative;
  height: 16px; 
  height: 1em; 
  border: 1px solid black; 
  border-radius: 10px; 
  overflow: hidden; 
  background: white;
}
.bar > div{
  position: absolute;
  top: 0;
  left: 0;
  background: green; 
  height: 16px; 
  height: 16px;
  z-index: 4;
  text-align: center;
  font-size: .7em;
  line-height: 16px;
  color: #000;
}
</style>
<table id='result_list'>
<thead>
    <tr>
        <th>{% trans 'Health fund' %}</th>
        <th width="200px">{% trans 'Progress' %}</th>
        <th>{% trans 'Action' %}</th>
    </tr>
</thead>
{% for participant in participant_list %}
    <tr>
        <td>{{participant.health_fund}}</td>
        <td>
        <div class="bar">
            <div style="width: {{participant.progress |floatformat:"0"}}%; ">{{participant.get_progress_display}}</div>
        </div>
        </td>
        <td><a href="{{participant.get_absolute_url}}">{% trans 'View' %}</a></td>
    </tr>
{% endfor %}
<tfooter>
    <tr>
        <th>&nbsp;</th>
        <th>
        <div class="bar">
            <div style="width: {{sum_progress |floatformat:"0"}}%; ">{{ sum_fill_count }} / {{ sum_required_count }}</div>
        </div>
        </th>
        <th>&nbsp;</th>
    </tr>
</tfooter>
</table>
{% endblock %}

survey/templates/survey/survey_admin_validate.html
{% extends 'survey/survey_admin_base.html' %}

{% block content %}
<ul>
{% for status,text in log %}
    <li>{{status|yesno:"OK,FAIL,--"}}: {{text}}</li>
{% endfor %}
</ul>
{% endblock %}

survey/templates/survey/survey_email.html
Szanowni Państwo,

Uprzejmie potwierdzamy zapisanie odpowiedzi {{participant.health_fund}} na pytania na temat "{{hospital}}". 
{% if linked_list_left %}
Pragniemy podkreślić, że wciąż oczekujemy na udzielenie odpowiedzi na temat {{linked_left}} z {{linked_total}} instytucji:{% for linked in linked_list_left %}
- {{linked.obj}} - {{linked.link}}{% endfor %}
{% endif %}
Poniżej przedstawiamy zestawienie udzielonych odpowiedzi na temat "{{hospital}}":
{% for category, question_set in object_list %}
# {{category}}
{% for question, subquestion_set in question_set %}## {{question}}
{% for subquestion, field in subquestion_set %}{{subquestion.name}}: {{field.0.answer}}
{% endfor %}
{% endfor %}
{% endfor %}
Z poważaniem,